name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'   # run on all PR source/target branches
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test test/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI.Tests/Microsoft.Azure.Functions.Worker.Extensions.OpenApi.CLI.Tests.csproj --configuration Release --no-build --logger trx
